SRE-1117 Error: Default profile needs to be set
snapsheet/homebrew-core pull request #9
Opened 2022-02-17 22:38 UTC by whatisdot

Closes https://snapsheettech.atlassian.net/browse/SRE-1117

This addresses a dependency issue that occurs when the local version of awscli conflicts with the version of awscli that Tinker depends upon.

We specify `awscli` version 2 as a [Homebrew dependency](https://docs.brew.sh/Formula-Cookbook#specifying-other-formulae-as-dependencies). When installed, Homebrew will explicitly include the library in the PATH that we write within the wrapper entrypoint for Tinker. This ensures the brew-installed version will take priority, without requiring the user to modify their PATH via .profile/.bashrc/.zshrc/etc.

# Testing
:point_right: Make sure you are on the main branch when you attempt to reproduce the issue.:point_left: 

## Linux
### Reproduce the Issue
Open a docker container in the dev environment.
```
docker compose build
docker compose run --rm cli
```

Install python 2.7 and make it the default.
```
sudo apt-add-repository universe && sudo apt update
sudo apt install -y python2-minimal
sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
```

Verify python 2.7 is the default.
```
python --version
```

Install pip for explicitly using python2.
```
curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output /tmp/get-pip.py
sudo python2 /tmp/get-pip.py
# verify pip uses python 2.7
pip --version
```

Install awscli v1
```
sudo apt-get install -y libyaml-dev libpython2.7-dev
pip install awscli==1.16.75
```

Confirm you have awscli v1 installed as default
```
source ~/.profile
aws --version # should be "aws-cli/1.16.75"
```

Install awcli via homebrew (this will take several minutes)
```
brew install awscli
```

Verify the PATH resolution uses the old version
```
source ~/.profile
aws --version # should still be "aws-cli/1.16.75"
```

Run the tinker installer (this will take several minutes)
```
brew install --build-from-source Formula/tinker.rb
```

Reproduce the issue by running auth
```
tinker auth
# should log out "Default profile needs to be set"
```

### Verify the Fix
Uninstall tinker within the container.
```
brew uninstall tinker
```

Checkout this branch.
```
git checkout jSRE_1117-error-default-profile-needs-to
```

Run the updated tinker installer (this will take several minutes)
```
brew install --build-from-source Formula/tinker.rb
```

Verify auth will work as expected
```
tinker auth
# should prompt or do nothing
```

Verify the PATH resolution still uses the old version of awscli:
```
source ~/.profile
aws --version # should still be "aws-cli/1.16.75"
```

## MacOS
### Reproduce the Issue
Exit out of the docker container.

Verify that you are using the expected version of awscli:
```
aws --version # should be "aws-cli/1.16.75"
```

You should already have Tinker installed, so reproducing the issue should be easy. Run the following:
```
tinker auth
# should log out "Default profile needs to be set"
```

If it does not, remove tinker, reinstall it, and try again:
```
brew remove tinker
HOMEBREW_GITHUB_API_TOKEN=$GITHUB_TOKEN brew install tinker
tinker auth
# should log out "Default profile needs to be set"
```

### Verify the Fix
Remove Tinker:
```
brew remove tinker
```

Remove awscli v2 if you have it installed:
```
brew remove awscli
```

Verify you're version of awscli is still correctly using Python 2.7:
```
aws --version # should still be "aws-cli/1.16.75"
```

Run the updated tinker installer (this will take several minutes)
```
HOMEBREW_GITHUB_API_TOKEN=$GITHUB_TOKEN brew install --build-from-source Formula/tinker.rb
```
You should see `awscli` being installed as a dependency:
```
==> Installing dependencies for tinker: awscli
==> Installing tinker dependency: awscli
==> Pouring awscli--2.4.18.monterey.bottle.tar.gz
```

Verify auth will work as expected
```
tinker auth
# should prompt or do nothing
```

Verify the default PATH still uses the old version of awscli:
```
aws --version # should still be "aws-cli/1.16.75"
```

Attempt to uninstall awscli and verify that Homebrew will raise a dependency error:
```
brew remove awscli
```
```
Error: Refusing to uninstall /usr/local/Cellar/awscli/2.4.18
because it is required by tinker, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies awscli
```

## Cleanup

Uninstall the dev version of the formula from your host.
```
brew remove tinker
```

2022-02-18 23:00 UTC, d10zero requested changes
When testing in Linux, at the very end of the test steps when confirming the `aws --version`, I received something different than the expected output: 
```
dev.user@52cd203d045e:~/homebrew-core$ aws --version
aws-cli/2.4.19 Python/3.9.10 Linux/5.10.76-linuxkit source/x86_64.ubuntu.20 prompt/off
```

2022-02-22 17:21 UTC, whatisdot commented
@d10zero unable to reproduce.

Can you post the steps that you used, starting with checking out the `main` branch and starting a new container?

2022-02-25 21:04 UTC, d10zero approved these changes
These are the test steps that I followed, all looks good!
```
docker compose run --rm cli

sudo apt-add-repository universe && sudo apt update
sudo apt install -y python2-minimal
sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1

python --version

curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output /tmp/get-pip.py
sudo python2 /tmp/get-pip.py
# verify pip uses python 2.7
pip --version

sudo apt-get install -y libyaml-dev libpython2.7-dev
pip install awscli==1.16.75

source ~/.profile
aws --version # should be "aws-cli/1.16.75"
brew install awscli
source ~/.profile
aws --version # should still be "aws-cli/1.16.75"
brew install --build-from-source Formula/tinker.rb
tinker auth # worked correctly and requested MFA
brew uninstall tinker

git checkout main
brew install --build-from-source Formula/tinker.rb
tinker auth # did not request MFA and printed `Tinker -- Default profile needs to be set`
source ~/.profile
aws --version # should still be "aws-cli/1.16.75"
```

2022-03-01 17:03 UTC, whatisdot commented
After speaking with @d10zero we figured out that starting the container while on the `main` branch will not mount the `~/.aws` directory. This causes `tinker auth` to fail, regardless of how it was installed.

I've updated the testing steps in the PR description to what @d10zero provided.

2022-03-01 17:40 UTC, deekom approved these changes
Changes look good, worked for me with updated instructions.

2022-03-01 17:40 UTC, merged